// 事件類別對應中文
export const categoryLabels: Record<string, string> = {
  ERP: 'ERP',
  AUP: '計畫書',
  ANIMAL: '實驗動物',
  SYSTEM: '系統',
}

// 事件類型對應中文顯示
export const eventTypeLabels: Record<string, { label: string; color: string }> = {
  // 通用操作
  DOC_CREATE: { label: '建立單據', color: 'bg-status-success-text' },
  DOC_UPDATE: { label: '更新單據', color: 'bg-status-info-text' },
  DOC_DELETE: { label: '刪除單據', color: 'bg-status-error-text' },
  DOC_SUBMIT: { label: '送審單據', color: 'bg-status-warning-text' },
  DOC_APPROVE: { label: '核准單據', color: 'bg-status-purple-text' },
  DOC_CANCEL: { label: '作廢單據', color: 'bg-status-neutral-text' },
  PARTNER_CREATE: { label: '建立夥伴', color: 'bg-status-success-text' },
  PARTNER_UPDATE: { label: '更新夥伴', color: 'bg-status-info-text' },
  PARTNER_DELETE: { label: '刪除夥伴', color: 'bg-status-error-text' },
  PRODUCT_CREATE: { label: '建立產品', color: 'bg-status-success-text' },
  PRODUCT_UPDATE: { label: '更新產品', color: 'bg-status-info-text' },
  PRODUCT_DELETE: { label: '刪除產品', color: 'bg-status-error-text' },
  CATEGORY_CREATE: { label: '建立分類', color: 'bg-status-success-text' },
  WAREHOUSE_CREATE: { label: '建立倉庫', color: 'bg-status-success-text' },
  WAREHOUSE_UPDATE: { label: '更新倉庫', color: 'bg-status-info-text' },
  WAREHOUSE_DELETE: { label: '刪除倉庫', color: 'bg-status-error-text' },
  ROLE_CREATE: { label: '建立角色', color: 'bg-status-success-text' },
  ROLE_UPDATE: { label: '更新角色', color: 'bg-status-info-text' },
  ROLE_DELETE: { label: '刪除角色', color: 'bg-status-error-text' },
  // 動物管理
  ANIMAL_CREATE: { label: '建立動物', color: 'bg-status-success-text' },
  ANIMAL_UPDATE: { label: '更新動物', color: 'bg-status-info-text' },
  ANIMAL_DELETE: { label: '刪除動物', color: 'bg-status-error-text' },
  ANIMAL_BATCH_ASSIGN: { label: '批次分配', color: 'bg-status-purple-text' },
  OBSERVATION_CREATE: { label: '建立觀察', color: 'bg-status-success-text' },
  OBSERVATION_UPDATE: { label: '更新觀察', color: 'bg-status-info-text' },
  OBSERVATION_DELETE: { label: '刪除觀察', color: 'bg-status-error-text' },
  SURGERY_CREATE: { label: '建立手術', color: 'bg-status-success-text' },
  SURGERY_UPDATE: { label: '更新手術', color: 'bg-status-info-text' },
  SURGERY_DELETE: { label: '刪除手術', color: 'bg-status-error-text' },
  WEIGHT_CREATE: { label: '記錄體重', color: 'bg-status-success-text' },
  WEIGHT_UPDATE: { label: '更新體重', color: 'bg-status-info-text' },
  WEIGHT_DELETE: { label: '刪除體重', color: 'bg-status-error-text' },
  VACCINATION_CREATE: { label: '建立疫苗', color: 'bg-status-success-text' },
  VACCINATION_UPDATE: { label: '更新疫苗', color: 'bg-status-info-text' },
  VACCINATION_DELETE: { label: '刪除疫苗', color: 'bg-status-error-text' },
  SACRIFICE_UPSERT: { label: '犧牲/安樂死', color: 'bg-status-warning-text' },
  PATHOLOGY_UPSERT: { label: '病理報告', color: 'bg-status-purple-text' },
  VET_RECOMMENDATION_ADD: { label: '獸醫建議', color: 'bg-status-success-text' },
  MEDICAL_EXPORT: { label: '匯出醫療資料', color: 'bg-status-info-text' },
  BLOOD_TEST_CREATE: { label: '建立血液檢查', color: 'bg-status-success-text' },
  BLOOD_TEST_UPDATE: { label: '更新血液檢查', color: 'bg-status-info-text' },
  BLOOD_TEST_DELETE: { label: '刪除血液檢查', color: 'bg-status-error-text' },
  TEMPLATE_CREATE: { label: '建立模板', color: 'bg-status-success-text' },
  TEMPLATE_UPDATE: { label: '更新模板', color: 'bg-status-info-text' },
  TEMPLATE_DELETE: { label: '刪除模板', color: 'bg-status-error-text' },
  PANEL_CREATE: { label: '建立組合', color: 'bg-status-success-text' },
  PANEL_UPDATE: { label: '更新組合', color: 'bg-status-info-text' },
  PANEL_DELETE: { label: '刪除組合', color: 'bg-status-error-text' },
  // 計畫書
  PROTOCOL_CREATE: { label: '建立計畫書', color: 'bg-status-success-text' },
  PROTOCOL_UPDATE: { label: '更新計畫書', color: 'bg-status-info-text' },
  PROTOCOL_SUBMIT: { label: '送審計畫書', color: 'bg-status-warning-text' },
  PROTOCOL_APPROVE: { label: '核准計畫書', color: 'bg-status-purple-text' },
  PROTOCOL_REJECT: { label: '駁回計畫書', color: 'bg-status-error-text' },
  PROTOCOL_STATUS_CHANGE: { label: '狀態變更', color: 'bg-status-warning-text' },
  PROTOCOL_REVIEWER_ASSIGN: { label: '指派審查委員', color: 'bg-status-info-text' },
}

// 實體類型對應中文
export const entityTypeLabels: Record<string, string> = {
  document: '單據',
  partner: '夥伴',
  product: '產品',
  product_category: '產品分類',
  warehouse: '倉庫',
  role: '角色',
  animal: '動物',
  animal_observation: '觀察記錄',
  animal_surgery: '手術記錄',
  animal_weight: '體重記錄',
  animal_vaccination: '疫苗記錄',
  animal_sacrifice: '犧牲記錄',
  animal_pathology: '病理報告',
  animal_blood_test: '血液檢查',
  blood_test_template: '血檢模板',
  blood_test_panel: '血檢組合',
  vet_recommendation: '獸醫建議',
  protocol: '計畫書',
}

// 事件類別 → 可選實體類型 配對
export const categoryEntityMap: Record<string, { value: string; label: string }[]> = {
  all: [
    { value: 'document', label: '單據' },
    { value: 'product', label: '產品' },
    { value: 'warehouse', label: '倉庫' },
    { value: 'partner', label: '夥伴' },
    { value: 'blood_test_template', label: '血檢模板' },
    { value: 'blood_test_panel', label: '血檢組合' },
    { value: 'animal', label: '動物' },
    { value: 'animal_observation', label: '觀察記錄' },
    { value: 'animal_surgery', label: '手術記錄' },
    { value: 'animal_weight', label: '體重記錄' },
    { value: 'animal_vaccination', label: '疫苗記錄' },
    { value: 'animal_sacrifice', label: '犧牲記錄' },
    { value: 'animal_pathology', label: '病理報告' },
    { value: 'animal_blood_test', label: '血液檢查' },
    { value: 'vet_recommendation', label: '獸醫建議' },
    { value: 'protocol', label: '計畫書' },
    { value: 'role', label: '角色' },
  ],
  ERP: [
    { value: 'document', label: '單據' },
    { value: 'product', label: '產品' },
    { value: 'warehouse', label: '倉庫' },
    { value: 'partner', label: '夥伴' },
    { value: 'blood_test_template', label: '血檢模板' },
    { value: 'blood_test_panel', label: '血檢組合' },
  ],
  AUP: [
    { value: 'protocol', label: '計畫書' },
  ],
  ANIMAL: [
    { value: 'animal', label: '動物' },
    { value: 'animal_observation', label: '觀察記錄' },
    { value: 'animal_surgery', label: '手術記錄' },
    { value: 'animal_weight', label: '體重記錄' },
    { value: 'animal_vaccination', label: '疫苗記錄' },
    { value: 'animal_sacrifice', label: '犧牲記錄' },
    { value: 'animal_pathology', label: '病理報告' },
    { value: 'animal_blood_test', label: '血液檢查' },
    { value: 'vet_recommendation', label: '獸醫建議' },
  ],
}
