//! OpenAPI 文件入口 — Phase 1+2A+2B：Auth、Users、Roles、Facility、Warehouse、Protocol、電子簽章、動物管理
//!
//! 使用 utoipa 產生 Swagger/OpenAPI 3.0 規格。
//! 掛載 SwaggerUI 後可在 `/swagger-ui` 瀏覽互動式 API 文件。

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "iPIG ERP 後端 API",
        version = "0.1.0",
        description = "iPIG 實驗動物管理系統後端 API 文件",
        contact(name = "iPIG 開發團隊")
    ),
    paths(
        // === 認證 ===
        crate::handlers::auth::login,
        crate::handlers::auth::refresh_token,
        crate::handlers::auth::logout,
        crate::handlers::auth::me,
        crate::handlers::auth::update_me,
        crate::handlers::auth::change_own_password,
        crate::handlers::auth::confirm_password,
        crate::handlers::auth::forgot_password,
        crate::handlers::auth::reset_password_with_token,
        crate::handlers::auth::heartbeat,
        crate::handlers::auth::stop_impersonate,
        // === 使用者管理 ===
        crate::handlers::user::create_user,
        crate::handlers::user::list_users,
        crate::handlers::user::get_user,
        crate::handlers::user::update_user,
        crate::handlers::user::delete_user,
        crate::handlers::user::reset_user_password,
        crate::handlers::user::impersonate_user,
        // === 角色權限 ===
        crate::handlers::role::create_role,
        crate::handlers::role::list_roles,
        crate::handlers::role::get_role,
        crate::handlers::role::update_role,
        crate::handlers::role::delete_role,
        crate::handlers::role::list_permissions,
        // === 設施管理 ===
        crate::handlers::facility::list_species,
        crate::handlers::facility::get_species,
        crate::handlers::facility::create_species,
        crate::handlers::facility::update_species,
        crate::handlers::facility::delete_species,
        crate::handlers::facility::list_facilities,
        crate::handlers::facility::get_facility,
        crate::handlers::facility::create_facility,
        crate::handlers::facility::update_facility,
        crate::handlers::facility::delete_facility,
        crate::handlers::facility::list_buildings,
        crate::handlers::facility::get_building,
        crate::handlers::facility::create_building,
        crate::handlers::facility::update_building,
        crate::handlers::facility::delete_building,
        crate::handlers::facility::list_zones,
        crate::handlers::facility::get_zone,
        crate::handlers::facility::create_zone,
        crate::handlers::facility::update_zone,
        crate::handlers::facility::delete_zone,
        crate::handlers::facility::list_pens,
        crate::handlers::facility::get_pen,
        crate::handlers::facility::create_pen,
        crate::handlers::facility::update_pen,
        crate::handlers::facility::delete_pen,
        crate::handlers::facility::list_departments,
        crate::handlers::facility::get_department,
        crate::handlers::facility::create_department,
        crate::handlers::facility::update_department,
        crate::handlers::facility::delete_department,
        // === 倉儲管理 ===
        crate::handlers::warehouse::create_warehouse,
        crate::handlers::warehouse::list_warehouses,
        crate::handlers::warehouse::get_warehouse,
        crate::handlers::warehouse::update_warehouse,
        crate::handlers::warehouse::delete_warehouse,
        // === 計畫書管理 ===
        crate::handlers::protocol::crud::create_protocol,
        crate::handlers::protocol::crud::list_protocols,
        crate::handlers::protocol::crud::get_protocol,
        crate::handlers::protocol::crud::update_protocol,
        crate::handlers::protocol::crud::submit_protocol,
        crate::handlers::protocol::crud::change_protocol_status,
        crate::handlers::protocol::crud::get_protocol_versions,
        crate::handlers::protocol::crud::get_protocol_activities,
        crate::handlers::protocol::crud::assign_co_editor,
        crate::handlers::protocol::crud::list_co_editors,
        crate::handlers::protocol::crud::remove_co_editor,
        crate::handlers::protocol::crud::get_my_protocols,
        crate::handlers::protocol::crud::get_protocol_animal_stats,
        crate::handlers::protocol::crud::save_vet_review_form,
        crate::handlers::protocol::export::export_protocol_pdf,
        // === 審查管理 ===
        crate::handlers::protocol::review::assign_reviewer,
        crate::handlers::protocol::review::list_review_assignments,
        crate::handlers::protocol::review::create_review_comment,
        crate::handlers::protocol::review::list_review_comments,
        crate::handlers::protocol::review::resolve_review_comment,
        crate::handlers::protocol::review::reply_review_comment,
        crate::handlers::protocol::review::save_reply_draft,
        crate::handlers::protocol::review::get_reply_draft,
        crate::handlers::protocol::review::submit_reply_from_draft,
        // === 電子簽章 (GLP) ===
        crate::handlers::sign_sacrifice_record,
        crate::handlers::get_sacrifice_signature_status,
        crate::handlers::sign_observation_record,
        crate::handlers::sign_euthanasia_order,
        crate::handlers::get_euthanasia_signature_status,
        crate::handlers::sign_transfer_record,
        crate::handlers::get_transfer_signature_status,
        crate::handlers::sign_protocol_review,
        crate::handlers::get_protocol_signature_status,
        crate::handlers::add_record_annotation,
        crate::handlers::get_record_annotations,
        // === 動物管理 ===
        crate::handlers::list_animals,
        crate::handlers::list_animals_by_pen,
        crate::handlers::get_animal,
        crate::handlers::create_animal,
        crate::handlers::update_animal,
        crate::handlers::delete_animal,
        crate::handlers::batch_assign_animals,
        crate::handlers::mark_animal_vet_read,
        crate::handlers::get_animal_events,
    ),
    components(
        schemas(
            // 共用
            crate::error::ErrorResponse,
            crate::error::ErrorDetail,
            // User models
            crate::models::LoginRequest,
            crate::models::LoginResponse,
            crate::models::RefreshTokenRequest,
            crate::models::UserResponse,
            crate::models::CreateUserRequest,
            crate::models::UpdateUserRequest,
            crate::models::ChangeOwnPasswordRequest,
            crate::models::ConfirmPasswordRequest,
            crate::models::ResetPasswordRequest,
            crate::models::ForgotPasswordRequest,
            crate::models::ResetPasswordWithTokenRequest,
            crate::models::ThemePreference,
            crate::models::LanguagePreference,
            crate::models::UserTraining,
            // Role models
            crate::models::CreateRoleRequest,
            crate::models::UpdateRoleRequest,
            crate::models::RoleWithPermissions,
            crate::models::Permission,
            // Facility models
            crate::models::Species,
            crate::models::CreateSpeciesRequest,
            crate::models::UpdateSpeciesRequest,
            crate::models::Facility,
            crate::models::CreateFacilityRequest,
            crate::models::UpdateFacilityRequest,
            crate::models::Building,
            crate::models::BuildingWithFacility,
            crate::models::CreateBuildingRequest,
            crate::models::UpdateBuildingRequest,
            crate::models::Zone,
            crate::models::ZoneWithBuilding,
            crate::models::CreateZoneRequest,
            crate::models::UpdateZoneRequest,
            crate::models::Pen,
            crate::models::PenDetails,
            crate::models::CreatePenRequest,
            crate::models::UpdatePenRequest,
            crate::models::Department,
            crate::models::DepartmentWithManager,
            crate::models::CreateDepartmentRequest,
            crate::models::UpdateDepartmentRequest,
            // Warehouse models
            crate::models::Warehouse,
            crate::models::CreateWarehouseRequest,
            crate::models::UpdateWarehouseRequest,
            // Protocol models
            crate::models::Protocol,
            crate::models::ProtocolStatus,
            crate::models::ProtocolVersion,
            crate::models::ProtocolActivityType,
            crate::models::ProtocolActivity,
            crate::models::ProtocolActivityResponse,
            crate::models::ProtocolRole,
            crate::models::UserProtocol,
            crate::models::ReviewAssignment,
            crate::models::ReviewComment,
            crate::models::ProtocolAttachment,
            crate::models::VetReviewAssignment,
            crate::models::VetReviewItem,
            crate::models::VetReviewForm,
            crate::models::SystemSetting,
            crate::models::CreateProtocolRequest,
            crate::models::UpdateProtocolRequest,
            crate::models::ChangeStatusRequest,
            crate::models::AssignReviewerRequest,
            crate::models::AssignCoEditorRequest,
            crate::models::CreateCommentRequest,
            crate::models::ReplyCommentRequest,
            crate::models::SaveDraftRequest,
            crate::models::SubmitReplyRequest,
            crate::models::SaveVetReviewFormRequest,
            crate::models::ProtocolResponse,
            crate::models::ProtocolListItem,
            crate::models::ReviewCommentResponse,
            crate::models::ReviewAssignmentResponse,
            crate::models::CoEditorAssignmentResponse,
            // 電子簽章（經 handlers 再匯出）
            crate::handlers::SignRecordRequest,
            crate::handlers::SignRecordResponse,
            crate::handlers::CreateAnnotationRequest,
            crate::handlers::AnnotationResponse,
            crate::handlers::SignatureStatusResponse,
            crate::handlers::SignatureInfo,
            // 動物管理
            crate::models::Animal,
            crate::models::AnimalListItem,
            crate::models::AnimalQuery,
            crate::models::CreateAnimalRequest,
            crate::models::UpdateAnimalRequest,
            crate::models::AnimalsByPen,
            crate::models::BatchAssignRequest,
            crate::models::DeleteRequest,
            crate::models::AnimalStatus,
            crate::models::AnimalBreed,
            crate::models::AnimalGender,
            crate::handlers::AnimalEvent,
        )
    ),
    modifiers(),
    tags(
        (name = "認證", description = "登入、登出、Token 重整、密碼管理"),
        (name = "使用者管理", description = "使用者 CRUD、密碼重設、模擬登入"),
        (name = "角色權限", description = "角色 CRUD、權限查詢"),
        (name = "設施管理", description = "物種、設施、棟舍、區域、欄位、部門管理"),
        (name = "倉儲管理", description = "倉庫 CRUD"),
        (name = "計畫書管理", description = "專案 CRUD、狀態變更、版本、活動歷程、Co-Editor"),
        (name = "審查管理", description = "審查委員指派、審查意見、草稿、獸醫審查表"),
        (name = "電子簽章", description = "犧牲／觀察／安樂死／轉讓／計畫書簽章與附註 (GLP)"),
        (name = "動物管理", description = "動物 CRUD、依欄位查詢、批次分配、獸醫已讀、事件歷程"),
    ),
    security(
        ("bearer" = [])
    )
)]
pub struct ApiDoc;
